name: Build and Push Docker Image and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: prod-branch-deploy
  cancel-in-progress: true

jobs:
  react_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t 8pin/imos:nginx -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Push Docker image
      run: |
        docker push 8pin/imos:nginx

  deploy:
    runs-on: [self-hosted, terbotForAWS]
    needs:
      - react_build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into server and execute commands
      run: |
        echo "${{ secrets.SSH_AWS_KEY }}" > my_ec2_key.pem
        chmod 600 my_ec2_key.pem
        ssh -o StrictHostKeyChecking=no -i my_ec2_key.pem ${{ secrets.SSH_AWS_USER }}@${{ secrets.SSH_AWS_IP }} << 'EOF'
        
        echo "AWS SSH pem.key 접속 성공"
        whoami
        
        docker stop nginx_container || true
        docker rm nginx_container || true
        docker pull 8pin/imos:nginx:latest
        docker run -d \
          --name nginx_container \
          --network imosNetwork \
          -p 80:80 \
          8pin/imos:nginx
        EOF
