name: Build and Push Docker Image and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: prod-branch-deploy
  cancel-in-progress: true

jobs:
  react_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t 8pin/imos:nginx:latest -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_PWD }}

    - name: Push Docker image
      run: |
        docker push 8pin/imos:nginx:latest

  deploy:
    runs-on: [self-hosted, terbotForAWS]
    needs:
      - react_build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Decode SSH Key
#      run: |
#        echo "${{ secrets.KEY_B64 }}" | base64 -d > key.pem
#        chmod 600 key.pem

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop nginx_container || true
          docker rm nginx_container || true
          docker pull 8pin/imos:nginx:latest
          docker run -d \
            --name nginx_container \
            --network imosNetwork \
            -p 80:80 \
            8pin/imos:nginx:latest
          docker system prune -a -f